Repository charybdis-ircd/charybdis, pull requests merged in 2020-07, with the labels that each got.

#344 Actually use modules' declared hook priorities
  ircd/modules.c
Labels: bug

#345 m_alias: Preserve protocol framing characters
  include/msgbuf.h
  ircd/msgbuf.c
  modules/m_alias.c
  tests/msgbuf_parse1.c
Labels: enhancement

#342 modularize callerid
  extensions/umode_noctcp.c
  help/opers/umode
  help/users/umode
  include/client.h
  include/messages.h
  include/supported.h
  ircd/newconf.c
  ircd/s_user.c
  ircd/supported.c
  modules/Makefile.am
  modules/core/m_message.c
  modules/m_invite.c
  modules/um_callerid.c
Labels: enhancement

#353 m_privs: don't leave a damaged privset behind
  modules/m_privs.c
Labels: bug, missed-in-review

#352 m_grant: zero-initialize struct oper_conf
  modules/m_grant.c
Labels: bug
