Repository charybdis-ircd/charybdis, pull requests merged in 2020-06, with the labels that each got.

#338 m_kline: insert a safety zero early
  modules/m_kline.c
Labels: bug

#329 Reload modules by path
  include/modules.h
  ircd/modules.c
Labels: enhancement

#328 capability: accept new ownerdata for existing caps
  ircd/capability.c
Labels: bug, enhancement

#322 m_invite: Don't punch through +g
  modules/m_invite.c
Labels: bug

#334 Remove the massnotice wildcard restriction
  modules/core/m_message.c
Labels: enhancement

#333 m_privs: break long responses into multiple lines
  modules/m_privs.c
Labels: bug

#343 m_ison: Do not report unregistered connections
  modules/m_ison.c
Labels: bug
